# Generated by Django 3.1.3 on 2021-04-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_administrador_user'),
        ('productos', '0002_auto_20210315_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comidas',
            name='direccion_envio',
        ),
        migrations.AddField(
            model_name='comidas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comidas',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comidas',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='comidas',
            name='id_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.vendedor'),
        ),
    ]
