# Generated by Django 3.1.3 on 2021-04-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20210406_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='calorias_totales',
            field=models.FloatField(default=0),
        ),
    ]
