# Generated by Django 3.1.3 on 2021-04-06 17:34

from django.db import migrations, models
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20210406_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.get_upload_to_categoria),
        ),
        migrations.AlterField(
            model_name='comidas',
            name='imagen',
            field=models.ImageField(upload_to=productos.models.get_upload_to_comida),
        ),
    ]
