# Generated by Django 3.1.3 on 2021-06-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20210406_1734'),
        ('general', '0002_perfil_id_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilParametrizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cabecera', models.CharField(max_length=200)),
                ('detalle', models.CharField(max_length=200)),
                ('peso_mode_comparator', models.IntegerField()),
                ('peso_minimo', models.FloatField()),
                ('peso_maximo', models.FloatField()),
                ('altura_mode_comparator', models.IntegerField()),
                ('altura_minimo', models.FloatField()),
                ('altura_maximo', models.FloatField()),
                ('imc_mode_comparator', models.IntegerField()),
                ('imc_minimo', models.FloatField()),
                ('imc_maximo', models.FloatField()),
            ],
            options={
                'verbose_name': 'PerfilParametrizado',
            },
        ),
        migrations.CreateModel(
            name='CategoriasPerfilParametrizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.categoria')),
                ('perfil_parametrizado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.perfilparametrizado')),
            ],
            options={
                'verbose_name': 'CategoriasPerfilParametrizado',
            },
        ),
    ]
'''
        migrations.CreateModel(
            name='PerfilE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Perfil_E',
            },
        ),
        '''