# Generated by Django 3.1.3 on 2021-06-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20210406_1734'),
        ('general', '0003_categoriasperfilparametrizado_perfile_perfilparametrizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilparametrizado',
            name='cabecera',
        ),
        migrations.RemoveField(
            model_name='perfilparametrizado',
            name='detalle',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='perfil_defecto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.perfilparametrizado'),
        ),
        migrations.AlterField(
            model_name='categoriasperfilparametrizado',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='categoriasperfilparametrizado',
            name='perfil_parametrizado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.perfilparametrizado'),
        ),
        migrations.AlterField(
            model_name='perfilparametrizado',
            name='altura_maximo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilparametrizado',
            name='altura_minimo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilparametrizado',
            name='altura_mode_comparator',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='perfilparametrizado',
            name='imc_maximo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilparametrizado',
            name='imc_minimo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilparametrizado',
            name='imc_mode_comparator',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='perfilparametrizado',
            name='peso_maximo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilparametrizado',
            name='peso_minimo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilparametrizado',
            name='peso_mode_comparator',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='categoriasperfilparametrizado',
            unique_together={('perfil_parametrizado', 'categoria')},
        ),
    ]
