# Generated by Django 3.2 on 2021-04-24 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_administrador_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
    ]
